In [3]:
from PIL import Image #loading the dependencies
import numpy as np
import sys
import os
import csv

# default format can be changed as needed
def createFileList(myDir, format='.jpg'):
    fileList = []
    print(myDir)
    for root, dirs, files in os.walk(myDir, topdown=False):
        for name in files:
            if name.endswith(format):
                fullName = os.path.join(root, name)
                fileList.append(fullName)
    return fileList

# load the original image
myFileList = createFileList("to_be_converted")

for file in myFileList:
    print(file)
    img_file = Image.open(file)
    # img_file.show()

    # get original image parameters...
    width, height = img_file.size
    format = img_file.format
    mode = img_file.mode

    # Make image Greyscale
    img_grey = img_file.convert('L')
    #img_grey.save('result.png')
    #img_grey.show()

    # Save Greyscale values
    value = np.asarray(img_grey.getdata(), dtype=np.int).reshape((img_grey.size[1], img_grey.size[0]))
    value = value.flatten()
    print(value)
    with open("hand_emojis_final2.csv", 'a') as f:
        writer = csv.writer(f)
        writer.writerow(value)




to_be_converted
to_be_converted\1\gestures11.jpg
[1 2 0 ... 0 0 0]
to_be_converted\1\gestures110.jpg
[0 0 0 ... 1 0 0]
to_be_converted\1\gestures1100.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11000.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11001.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11002.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11003.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11004.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11005.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11006.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11007.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11008.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11009.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1101.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11010.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11011.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11012.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11013.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\g

to_be_converted\1\gestures11140.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11141.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11142.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11143.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11144.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11145.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11146.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11147.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11148.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11149.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1115.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11150.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11151.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11152.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11153.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11154.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11155.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures11156.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures111

[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1203.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1204.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1205.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1206.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1207.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1208.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1209.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures121.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1210.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1211.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1212.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1213.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1214.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1215.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1216.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1217.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1218.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1219.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures122

[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1345.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1346.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1347.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1348.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1349.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures135.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1350.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1351.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1352.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1353.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1354.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1355.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1356.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1357.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1358.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1359.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures136.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1360.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1361

[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1491.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1492.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1493.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1494.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1495.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1496.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1497.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1498.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1499.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures15.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures150.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1500.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1501.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1502.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1503.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1504.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1505.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1506.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1507.

[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1637.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1638.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1639.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures164.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1640.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1641.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1642.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1643.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1644.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1645.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1646.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1647.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1648.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1649.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures165.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1650.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1651.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1652.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1653

[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1783.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1784.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1785.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1786.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1787.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1788.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1789.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures179.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1790.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1791.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1792.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1793.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1794.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1795.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1796.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1797.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1798.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1799.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures18.

to_be_converted\1\gestures1926.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1927.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1928.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1929.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures193.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1930.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1931.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1932.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1933.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1934.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1935.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1936.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1937.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1938.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1939.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures194.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1940.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1941.jpg
[0 0 0 ... 0 0 0]
to_be_converted\1\gestures1942.jpg
[0 0 0 ... 0 

[  0   0   0 ... 255 222   0]
to_be_converted\10\gestures101051.jpg
[  0   0   0 ... 255 255   0]
to_be_converted\10\gestures101052.jpg
[  0   0   0 ... 255 255   0]
to_be_converted\10\gestures101053.jpg
[  0   0   0 ... 255 255  31]
to_be_converted\10\gestures101054.jpg
[  0   0   0 ... 255 255  31]
to_be_converted\10\gestures101055.jpg
[  0   0   0 ... 255   0   0]
to_be_converted\10\gestures101056.jpg
[  0   0   0 ... 255   0   0]
to_be_converted\10\gestures101057.jpg
[  0   0   0 ... 255 255   0]
to_be_converted\10\gestures101058.jpg
[  0   0   0 ... 255 255   0]
to_be_converted\10\gestures101059.jpg
[  0   0   0 ... 254 255 255]
to_be_converted\10\gestures10106.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures101060.jpg
[  0   0   0 ... 254 255 255]
to_be_converted\10\gestures101061.jpg
[  0   0   0 ... 255 255   0]
to_be_converted\10\gestures101062.jpg
[  0   0   0 ... 255 255   0]
to_be_converted\10\gestures101063.jpg
[  0   0   0 ... 255   0   0]
to_be_converted\10\

[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures101160.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures101161.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures101162.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures101163.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures101164.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures101165.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures101166.jpg
[  0   0   0 ... 255 255 106]
to_be_converted\10\gestures101167.jpg
[  0   0   0 ... 255 255 106]
to_be_converted\10\gestures101168.jpg
[  0   0   0 ... 255 253 255]
to_be_converted\10\gestures101169.jpg
[  0   0   0 ... 255 253 255]
to_be_converted\10\gestures10117.jpg
[  0   0   0 ... 255 255 219]
to_be_converted\10\gestures101170.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures101171.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures101172.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\

to_be_converted\10\gestures10195.jpg
[  0   0   0 ... 255   0   0]
to_be_converted\10\gestures10196.jpg
[  0   0   0 ... 252   0   0]
to_be_converted\10\gestures10197.jpg
[  0   0   0 ... 255   0   0]
to_be_converted\10\gestures10198.jpg
[  0   0   0 ... 255   0   0]
to_be_converted\10\gestures10199.jpg
[  0   0   0 ... 255   0   0]
to_be_converted\10\gestures102.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures1020.jpg
[  0   0   0 ... 255 255   0]
to_be_converted\10\gestures10200.jpg
[  0   0   0 ... 255   0   0]
to_be_converted\10\gestures10201.jpg
[  0   0   0 ... 255   0   0]
to_be_converted\10\gestures10202.jpg
[  0   0   0 ... 255   0   0]
to_be_converted\10\gestures10203.jpg
[  0   0   0 ... 255   0   0]
to_be_converted\10\gestures10204.jpg
[  0   0   0 ... 255 255   0]
to_be_converted\10\gestures10205.jpg
[  0   0   0 ... 255 255   0]
to_be_converted\10\gestures10206.jpg
[  0   0   0 ... 255   0   0]
to_be_converted\10\gestures10207.jpg
[  0   0   0 ... 255   0   0

[0 0 0 ... 3 0 0]
to_be_converted\10\gestures10313.jpg
[0 0 0 ... 3 0 0]
to_be_converted\10\gestures10314.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10315.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10316.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10317.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10318.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10319.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures1032.jpg
[  0   0   0 ... 255 254   5]
to_be_converted\10\gestures10320.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10321.jpg
[  0   0   0 ... 252 255 255]
to_be_converted\10\gestures10322.jpg
[  0   0   0 ... 252 255 255]
to_be_converted\10\gestures10323.jpg
[ 0  0  0 ... 34 38 38]
to_be_converted\10\gestures10324.jpg
[ 0  0  0 ... 34 38 38]
to_be_converted\10\gestures10325.jpg
[  0   0   0 ... 255  76  76]
to_be_converted\10\gestures10326.jpg
[  0   0   0 ... 255  76  76]
to

to_be_converted\10\gestures10432.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10433.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10434.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10435.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10436.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10437.jpg
[  0   0   0 ... 255 254 255]
to_be_converted\10\gestures10438.jpg
[  0   0   0 ... 255 254 253]
to_be_converted\10\gestures10439.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures1044.jpg
[  0   0   0 ... 255 253 246]
to_be_converted\10\gestures10440.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10441.jpg
[  0   0   0 ... 255 254 254]
to_be_converted\10\gestures10442.jpg
[  0   0   0 ... 255 254 254]
to_be_converted\10\gestures10443.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10444.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10445.jpg
[  0   0   0 ... 255 255 2

[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10543.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10544.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10545.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10546.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10547.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10548.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10549.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures1055.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10550.jpg
[  0   0   0 ... 255 251 230]
to_be_converted\10\gestures10551.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10552.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10553.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10554.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10555.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10556.

to_be_converted\10\gestures10658.jpg
[  0   0   0 ... 255 254 255]
to_be_converted\10\gestures10659.jpg
[  0   0   0 ... 255 254 255]
to_be_converted\10\gestures1066.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10660.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10661.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10662.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10663.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10664.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10665.jpg
[  0   0   0 ... 255 255 249]
to_be_converted\10\gestures10666.jpg
[  0   0   0 ... 255 255 249]
to_be_converted\10\gestures10667.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10668.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10669.jpg
[  0   0   0 ... 255 255 251]
to_be_converted\10\gestures1067.jpg
[  0   0   0 ... 255 255  65]
to_be_converted\10\gestures10670.jpg
[  0   0   0 ... 255 255 25

[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10770.jpg
[  0   0   0 ... 255   1   1]
to_be_converted\10\gestures10771.jpg
[  0   0   0 ... 255   1   1]
to_be_converted\10\gestures10772.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10773.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10774.jpg
[  0   0   0 ... 255 254   0]
to_be_converted\10\gestures10775.jpg
[  0   0   0 ... 255 254   0]
to_be_converted\10\gestures10776.jpg
[  0   0   0 ... 255   4   0]
to_be_converted\10\gestures10777.jpg
[  0   0   0 ... 255   4   0]
to_be_converted\10\gestures10778.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10779.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures1078.jpg
[  0   0   0 ... 252 249   0]
to_be_converted\10\gestures10780.jpg
[  0   0   0 ... 255 254   0]
to_be_converted\10\gestures10781.jpg
[  0   0   0 ... 255 254   0]
to_be_converted\10\gestures10782.jpg
[  0   0   0 ... 255 255   6]
to_be_converted\10\gestures10783.

to_be_converted\10\gestures10891.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10892.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10893.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10894.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10895.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10896.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10897.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10898.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10899.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures109.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures1090.jpg
[  0   0   0 ... 255 255  44]
to_be_converted\10\gestures10900.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10901.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10902.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\10\gestures10903.jpg
[  0   0   0 ... 255 255 255

to_be_converted\2\gestures21007.jpg
[1 0 0 ... 3 0 0]
to_be_converted\2\gestures21008.jpg
[1 0 0 ... 3 0 0]
to_be_converted\2\gestures21009.jpg
[0 3 0 ... 0 0 0]
to_be_converted\2\gestures2101.jpg
[1 0 1 ... 0 0 0]
to_be_converted\2\gestures21010.jpg
[0 1 2 ... 0 0 0]
to_be_converted\2\gestures21011.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures21012.jpg
[0 2 0 ... 0 0 0]
to_be_converted\2\gestures21013.jpg
[0 2 0 ... 0 0 0]
to_be_converted\2\gestures21014.jpg
[0 2 0 ... 0 0 0]
to_be_converted\2\gestures21015.jpg
[0 0 0 ... 1 0 0]
to_be_converted\2\gestures21016.jpg
[2 0 1 ... 1 0 0]
to_be_converted\2\gestures21017.jpg
[0 0 0 ... 1 0 0]
to_be_converted\2\gestures21018.jpg
[0 5 0 ... 0 0 0]
to_be_converted\2\gestures21019.jpg
[0 0 2 ... 1 0 0]
to_be_converted\2\gestures2102.jpg
[2 0 0 ... 4 0 0]
to_be_converted\2\gestures21020.jpg
[0 0 2 ... 1 0 0]
to_be_converted\2\gestures21021.jpg
[0 2 0 ... 0 0 0]
to_be_converted\2\gestures21022.jpg
[0 0 2 ... 0 0 0]
to_be_converted\2\gestures2102

[  0   1   1 ... 255 255 255]
to_be_converted\2\gestures21150.jpg
[0 1 1 ... 0 0 0]
to_be_converted\2\gestures21151.jpg
[0 2 0 ... 0 0 0]
to_be_converted\2\gestures21152.jpg
[0 0 2 ... 0 0 0]
to_be_converted\2\gestures21153.jpg
[0 4 0 ... 1 0 0]
to_be_converted\2\gestures21154.jpg
[1 0 0 ... 0 0 0]
to_be_converted\2\gestures21155.jpg
[0 0 1 ... 0 0 0]
to_be_converted\2\gestures21156.jpg
[0 1 0 ... 0 0 0]
to_be_converted\2\gestures21157.jpg
[2 0 0 ... 0 0 0]
to_be_converted\2\gestures21158.jpg
[2 0 0 ... 0 0 0]
to_be_converted\2\gestures21159.jpg
[2 0 0 ... 0 0 0]
to_be_converted\2\gestures2116.jpg
[  0   0   2 ... 255 252 127]
to_be_converted\2\gestures21160.jpg
[2 0 1 ... 0 0 0]
to_be_converted\2\gestures21161.jpg
[1 0 0 ... 1 0 0]
to_be_converted\2\gestures21162.jpg
[0 0 1 ... 0 0 0]
to_be_converted\2\gestures21163.jpg
[2 0 1 ... 1 0 0]
to_be_converted\2\gestures21164.jpg
[2 0 1 ... 1 0 0]
to_be_converted\2\gestures21165.jpg
[0 0 1 ... 2 0 0]
to_be_converted\2\gestures21166.jpg
[1 0 

[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2197.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2198.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2199.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures22.jpg
[  0   1   0 ... 255  30   1]
to_be_converted\2\gestures220.jpg
[0 1 0 ... 0 0 0]
to_be_converted\2\gestures2200.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2201.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2202.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2203.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2204.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2205.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2206.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2207.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2208.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2209.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures221.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2210.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2211.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\ge

to_be_converted\2\gestures2326.jpg
[0 1 0 ... 0 0 0]
to_be_converted\2\gestures2327.jpg
[0 2 0 ... 0 0 0]
to_be_converted\2\gestures2328.jpg
[1 0 1 ... 0 0 0]
to_be_converted\2\gestures2329.jpg
[1 0 1 ... 0 0 0]
to_be_converted\2\gestures233.jpg
[0 0 2 ... 0 0 0]
to_be_converted\2\gestures2330.jpg
[0 0 2 ... 3 0 0]
to_be_converted\2\gestures2331.jpg
[0 0 0 ... 2 0 0]
to_be_converted\2\gestures2332.jpg
[0 0 0 ... 2 0 0]
to_be_converted\2\gestures2333.jpg
[1 0 1 ... 0 0 0]
to_be_converted\2\gestures2334.jpg
[2 0 0 ... 0 0 0]
to_be_converted\2\gestures2335.jpg
[2 0 0 ... 0 0 0]
to_be_converted\2\gestures2336.jpg
[2 0 3 ... 0 0 0]
to_be_converted\2\gestures2337.jpg
[0 1 0 ... 2 0 0]
to_be_converted\2\gestures2338.jpg
[0 0 1 ... 0 0 0]
to_be_converted\2\gestures2339.jpg
[0 1 0 ... 0 0 0]
to_be_converted\2\gestures234.jpg
[1 1 1 ... 0 0 0]
to_be_converted\2\gestures2340.jpg
[0 3 0 ... 0 0 0]
to_be_converted\2\gestures2341.jpg
[  0   1   0 ... 254   0   0]
to_be_converted\2\gestures2342.jpg
[

[1 0 1 ... 0 0 0]
to_be_converted\2\gestures2461.jpg
[0 1 0 ... 0 0 0]
to_be_converted\2\gestures2462.jpg
[0 0 4 ... 0 0 0]
to_be_converted\2\gestures2463.jpg
[0 0 4 ... 0 0 0]
to_be_converted\2\gestures2464.jpg
[0 0 4 ... 0 0 0]
to_be_converted\2\gestures2465.jpg
[0 2 0 ... 0 0 0]
to_be_converted\2\gestures2466.jpg
[0 2 0 ... 0 0 0]
to_be_converted\2\gestures2467.jpg
[1 0 0 ... 0 0 0]
to_be_converted\2\gestures2468.jpg
[0 0 1 ... 0 0 0]
to_be_converted\2\gestures2469.jpg
[0 0 1 ... 0 0 0]
to_be_converted\2\gestures247.jpg
[2 0 2 ... 0 0 0]
to_be_converted\2\gestures2470.jpg
[2 0 2 ... 2 0 0]
to_be_converted\2\gestures2471.jpg
[0 0 1 ... 0 0 0]
to_be_converted\2\gestures2472.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2473.jpg
[0 1 1 ... 0 0 0]
to_be_converted\2\gestures2474.jpg
[0 1 1 ... 0 0 0]
to_be_converted\2\gestures2475.jpg
[1 0 0 ... 0 0 0]
to_be_converted\2\gestures2476.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2477.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures247

to_be_converted\2\gestures2591.jpg
[1 0 1 ... 0 0 0]
to_be_converted\2\gestures2592.jpg
[1 0 1 ... 0 0 0]
to_be_converted\2\gestures2593.jpg
[0 0 2 ... 1 0 0]
to_be_converted\2\gestures2594.jpg
[0 0 1 ... 1 0 0]
to_be_converted\2\gestures2595.jpg
[0 1 1 ... 3 0 0]
to_be_converted\2\gestures2596.jpg
[0 1 1 ... 3 0 0]
to_be_converted\2\gestures2597.jpg
[0 1 0 ... 0 0 0]
to_be_converted\2\gestures2598.jpg
[1 0 0 ... 1 0 0]
to_be_converted\2\gestures2599.jpg
[0 0 0 ... 4 0 0]
to_be_converted\2\gestures26.jpg
[  2   0   1 ... 255 255   0]
to_be_converted\2\gestures260.jpg
[0 2 0 ... 1 0 0]
to_be_converted\2\gestures2600.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2601.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2602.jpg
[0 1 0 ... 0 0 0]
to_be_converted\2\gestures2603.jpg
[1 1 0 ... 0 0 0]
to_be_converted\2\gestures2604.jpg
[ 22 255 254 ...   0   0   0]
to_be_converted\2\gestures2605.jpg
[ 22 255 254 ...   0   0   0]
to_be_converted\2\gestures2606.jpg
[0 2 0 ... 0 0 0]
to_be_convert

[ 0 26 25 ...  0  0  0]
to_be_converted\2\gestures2726.jpg
[ 0 26 25 ...  0  0  0]
to_be_converted\2\gestures2727.jpg
[1 0 0 ... 0 0 0]
to_be_converted\2\gestures2728.jpg
[0 3 0 ... 0 0 0]
to_be_converted\2\gestures2729.jpg
[ 0 26 25 ...  0  0  0]
to_be_converted\2\gestures273.jpg
[0 1 0 ... 0 0 0]
to_be_converted\2\gestures2730.jpg
[0 1 0 ... 0 0 0]
to_be_converted\2\gestures2731.jpg
[1 2 0 ... 0 0 0]
to_be_converted\2\gestures2732.jpg
[0 1 0 ... 0 0 0]
to_be_converted\2\gestures2733.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2734.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2735.jpg
[0 0 1 ... 0 0 0]
to_be_converted\2\gestures2736.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2737.jpg
[ 0 28 29 ...  0  0  0]
to_be_converted\2\gestures2738.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2739.jpg
[ 0 26 25 ...  0  0  0]
to_be_converted\2\gestures274.jpg
[1 0 0 ... 0 0 0]
to_be_converted\2\gestures2740.jpg
[0 0 1 ... 0 0 0]
to_be_converted\2\gestures2741.jpg
[  1  26 255 ...  

[0 1 0 ... 0 0 0]
to_be_converted\2\gestures2866.jpg
[ 0 42 44 ...  0  0  0]
to_be_converted\2\gestures2867.jpg
[0 0 2 ... 0 0 0]
to_be_converted\2\gestures2868.jpg
[4 0 0 ... 0 0 0]
to_be_converted\2\gestures2869.jpg
[2 0 0 ... 0 0 0]
to_be_converted\2\gestures287.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2870.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2871.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2872.jpg
[  0 255 253 ...   1   0   0]
to_be_converted\2\gestures2873.jpg
[0 0 0 ... 2 0 0]
to_be_converted\2\gestures2874.jpg
[0 1 0 ... 0 0 0]
to_be_converted\2\gestures2875.jpg
[0 1 0 ... 0 0 0]
to_be_converted\2\gestures2876.jpg
[0 1 0 ... 0 0 0]
to_be_converted\2\gestures2877.jpg
[0 0 0 ... 0 0 0]
to_be_converted\2\gestures2878.jpg
[2 0 1 ... 0 0 0]
to_be_converted\2\gestures2879.jpg
[0 0 2 ... 0 0 0]
to_be_converted\2\gestures288.jpg
[0 2 0 ... 0 0 0]
to_be_converted\2\gestures2880.jpg
[0 0 2 ... 0 0 0]
to_be_converted\2\gestures2881.jpg
[ 1 41 41 ...  0  0  0]
to_be_

[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3100.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures31000.jpg
[0 0 0 ... 2 0 0]
to_be_converted\3\gestures31001.jpg
[0 0 0 ... 1 0 0]
to_be_converted\3\gestures31002.jpg
[0 0 0 ... 1 0 0]
to_be_converted\3\gestures31003.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures31004.jpg
[0 0 0 ... 2 0 0]
to_be_converted\3\gestures31005.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures31006.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures31007.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures31008.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures31009.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3101.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures31010.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures31011.jpg
[0 0 0 ... 1 0 0]
to_be_converted\3\gestures31012.jpg
[0 0 0 ... 1 0 0]
to_be_converted\3\gestures31013.jpg
[0 0 0 ... 1 0 0]
to_be_converted\3\gestures31014.jpg
[0 0 0 ... 1 0 0]
to_be_converted\3\gestures31015.jpg
[0 0 0 ... 0 0 0]
to_be_conver

to_be_converted\3\gestures31140.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures31141.jpg
[0 0 0 ... 1 0 0]
to_be_converted\3\gestures31142.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures31143.jpg
[0 0 0 ... 2 0 0]
to_be_converted\3\gestures31144.jpg
[0 0 0 ... 3 0 0]
to_be_converted\3\gestures31145.jpg
[0 0 0 ... 3 0 0]
to_be_converted\3\gestures31146.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures31147.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures31148.jpg
[0 0 0 ... 2 0 0]
to_be_converted\3\gestures31149.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3115.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures31150.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures31151.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures31152.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures31153.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures31154.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures31155.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures31156.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures311

[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3201.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3202.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3203.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3204.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3205.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3206.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3207.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3208.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3209.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures321.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3210.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3211.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3212.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3213.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3214.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3215.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3216.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3217.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures321

to_be_converted\3\gestures3341.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3342.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3343.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3344.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3345.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3346.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3347.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3348.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3349.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures335.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3350.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3351.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3352.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3353.jpg
[0 0 0 ... 2 0 0]
to_be_converted\3\gestures3354.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3355.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3356.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3357.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3358.jpg
[0 0 0 ... 0

[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3486.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3487.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3488.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3489.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures349.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3490.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3491.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3492.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3493.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3494.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3495.jpg
[0 0 0 ... 2 0 0]
to_be_converted\3\gestures3496.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3497.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3498.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3499.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures35.jpg
[1 0 0 ... 0 0 0]
to_be_converted\3\gestures350.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3500.jpg
[0 0 0 ... 2 0 0]
to_be_converted\3\gestures3501.j

[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3630.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3631.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3632.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3633.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3634.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3635.jpg
[0 0 0 ... 2 0 0]
to_be_converted\3\gestures3636.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3637.jpg
[0 0 0 ... 3 0 0]
to_be_converted\3\gestures3638.jpg
[0 0 0 ... 3 0 0]
to_be_converted\3\gestures3639.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures364.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3640.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3641.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3642.jpg
[0 0 0 ... 4 0 0]
to_be_converted\3\gestures3643.jpg
[0 0 0 ... 4 0 0]
to_be_converted\3\gestures3644.jpg
[0 0 0 ... 5 0 0]
to_be_converted\3\gestures3645.jpg
[0 0 0 ... 1 0 0]
to_be_converted\3\gestures3646.jpg
[0 0 0 ... 1 0 0]
to_be_converted\3\gestures364

to_be_converted\3\gestures3780.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3781.jpg
[0 0 0 ... 1 0 0]
to_be_converted\3\gestures3782.jpg
[0 0 0 ... 1 0 0]
to_be_converted\3\gestures3783.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3784.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3785.jpg
[0 0 0 ... 4 0 0]
to_be_converted\3\gestures3786.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3787.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3788.jpg
[0 0 0 ... 2 0 0]
to_be_converted\3\gestures3789.jpg
[0 0 0 ... 2 0 0]
to_be_converted\3\gestures379.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3790.jpg
[0 0 0 ... 2 0 0]
to_be_converted\3\gestures3791.jpg
[0 0 0 ... 2 0 0]
to_be_converted\3\gestures3792.jpg
[0 0 0 ... 2 0 0]
to_be_converted\3\gestures3793.jpg
[0 0 0 ... 2 0 0]
to_be_converted\3\gestures3794.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3795.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3796.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3797.jpg
[0 0 0 ... 2

[0 0 0 ... 1 0 0]
to_be_converted\3\gestures3924.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3925.jpg
[0 0 0 ... 2 0 0]
to_be_converted\3\gestures3926.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3927.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3928.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3929.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures393.jpg
[0 1 1 ... 0 0 0]
to_be_converted\3\gestures3930.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3931.jpg
[0 0 0 ... 1 0 0]
to_be_converted\3\gestures3932.jpg
[0 0 0 ... 1 0 0]
to_be_converted\3\gestures3933.jpg
[0 0 0 ... 1 0 0]
to_be_converted\3\gestures3934.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3935.jpg
[0 0 0 ... 1 0 0]
to_be_converted\3\gestures3936.jpg
[0 0 0 ... 1 0 0]
to_be_converted\3\gestures3937.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3938.jpg
[0 0 0 ... 0 0 0]
to_be_converted\3\gestures3939.jpg
[0 0 0 ... 1 0 0]
to_be_converted\3\gestures394.jpg
[0 1 1 ... 0 0 0]
to_be_converted\3\gestures3940

[  0   0   0 ... 255 255 235]
to_be_converted\4\gestures41052.jpg
[  2   0   1 ... 255 251   5]
to_be_converted\4\gestures41053.jpg
[  1   1   1 ... 255 255 255]
to_be_converted\4\gestures41054.jpg
[  0   0   2 ... 255 255 217]
to_be_converted\4\gestures41055.jpg
[  2   0   0 ... 255   0   0]
to_be_converted\4\gestures41056.jpg
[  1   0   0 ... 153   0   0]
to_be_converted\4\gestures41057.jpg
[2 0 0 ... 0 0 0]
to_be_converted\4\gestures41058.jpg
[0 0 2 ... 0 0 0]
to_be_converted\4\gestures41059.jpg
[0 0 1 ... 0 0 0]
to_be_converted\4\gestures4106.jpg
[  2   0   0 ... 255 253 255]
to_be_converted\4\gestures41060.jpg
[0 3 0 ... 0 0 0]
to_be_converted\4\gestures41061.jpg
[0 2 0 ... 0 0 0]
to_be_converted\4\gestures41062.jpg
[0 3 0 ... 0 0 0]
to_be_converted\4\gestures41063.jpg
[0 1 0 ... 0 0 0]
to_be_converted\4\gestures41064.jpg
[1 0 0 ... 0 0 0]
to_be_converted\4\gestures41065.jpg
[0 3 0 ... 0 0 0]
to_be_converted\4\gestures41066.jpg
[0 0 0 ... 0 0 0]
to_be_converted\4\gestures41067.jpg

[  2   0   0 ... 255 255 255]
to_be_converted\4\gestures41173.jpg
[  2   0   0 ... 255 255 255]
to_be_converted\4\gestures41174.jpg
[  2   0   2 ... 255 252 255]
to_be_converted\4\gestures41175.jpg
[  0   0   1 ... 255 254 122]
to_be_converted\4\gestures41176.jpg
[  0   3   2 ... 255 255 255]
to_be_converted\4\gestures41177.jpg
[  1   0   0 ... 255 255 255]
to_be_converted\4\gestures41178.jpg
[  1   0   0 ... 255 255 255]
to_be_converted\4\gestures41179.jpg
[  0   1   0 ... 255 255 255]
to_be_converted\4\gestures4118.jpg
[  0   3   0 ... 255 255   0]
to_be_converted\4\gestures41180.jpg
[  0   0   1 ... 255 255 255]
to_be_converted\4\gestures41181.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\4\gestures41182.jpg
[  0   3   0 ... 255 255 255]
to_be_converted\4\gestures41183.jpg
[  0   0   1 ... 255 255 255]
to_be_converted\4\gestures41184.jpg
[  0   0   2 ... 255 255 255]
to_be_converted\4\gestures41185.jpg
[  0   2   0 ... 255 255 255]
to_be_converted\4\gestures41186.jpg
[  2   0   

[  0   1   0 ... 255 254 226]
to_be_converted\4\gestures4225.jpg
[  1   0   1 ... 255 252 229]
to_be_converted\4\gestures4226.jpg
[  1   0   0 ... 255 255 220]
to_be_converted\4\gestures4227.jpg
[  0   0   2 ... 255 255 255]
to_be_converted\4\gestures4228.jpg
[  0   0   2 ... 255 255 255]
to_be_converted\4\gestures4229.jpg
[  1   0   3 ... 255 255 255]
to_be_converted\4\gestures423.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\4\gestures4230.jpg
[  0   0   2 ... 255 255 226]
to_be_converted\4\gestures4231.jpg
[  0   4   0 ... 255 255 251]
to_be_converted\4\gestures4232.jpg
[  0   0   2 ... 255 255 255]
to_be_converted\4\gestures4233.jpg
[  0   0   2 ... 255 255 255]
to_be_converted\4\gestures4234.jpg
[  0   3   0 ... 255 254 255]
to_be_converted\4\gestures4235.jpg
[  0   0   1 ... 255 255 255]
to_be_converted\4\gestures4236.jpg
[  1   0   2 ... 255 255 255]
to_be_converted\4\gestures4237.jpg
[  1   0   2 ... 255 255 255]
to_be_converted\4\gestures4238.jpg
[  1   0   0 ... 255 255 2

[  1   0   1 ... 255 255 255]
to_be_converted\4\gestures4341.jpg
[  1   0   1 ... 255 255 255]
to_be_converted\4\gestures4342.jpg
[  1   1   0 ... 255 255 255]
to_be_converted\4\gestures4343.jpg
[  2   0   0 ... 255 255 255]
to_be_converted\4\gestures4344.jpg
[  0   3   0 ... 255 253 173]
to_be_converted\4\gestures4345.jpg
[  2   0   0 ... 255 255 255]
to_be_converted\4\gestures4346.jpg
[  0   0   1 ... 255 255 255]
to_be_converted\4\gestures4347.jpg
[  0   2   0 ... 255 255 255]
to_be_converted\4\gestures4348.jpg
[  0   0   0 ... 255 253 255]
to_be_converted\4\gestures4349.jpg
[  0   0   0 ... 255 253 255]
to_be_converted\4\gestures435.jpg
[  1   2   0 ... 255 255 251]
to_be_converted\4\gestures4350.jpg
[  0   1   1 ... 255 255 255]
to_be_converted\4\gestures4351.jpg
[  2   0   0 ... 255 255 255]
to_be_converted\4\gestures4352.jpg
[  0   2   0 ... 255 255 255]
to_be_converted\4\gestures4353.jpg
[  0   1   0 ... 255 255  12]
to_be_converted\4\gestures4354.jpg
[  2   0   2 ... 255 255 2

[1 0 0 ... 0 0 0]
to_be_converted\4\gestures4474.jpg
[0 0 1 ... 0 0 0]
to_be_converted\4\gestures4475.jpg
[0 1 0 ... 0 0 0]
to_be_converted\4\gestures4476.jpg
[1 0 0 ... 0 0 0]
to_be_converted\4\gestures4477.jpg
[0 2 0 ... 0 0 0]
to_be_converted\4\gestures4478.jpg
[0 2 0 ... 0 0 0]
to_be_converted\4\gestures4479.jpg
[0 2 0 ... 0 0 0]
to_be_converted\4\gestures448.jpg
[  0   1   1 ... 255 255 255]
to_be_converted\4\gestures4480.jpg
[1 0 1 ... 0 0 0]
to_be_converted\4\gestures4481.jpg
[0 0 2 ... 0 0 0]
to_be_converted\4\gestures4482.jpg
[0 1 0 ... 0 0 0]
to_be_converted\4\gestures4483.jpg
[0 0 0 ... 0 0 0]
to_be_converted\4\gestures4484.jpg
[0 1 0 ... 0 0 0]
to_be_converted\4\gestures4485.jpg
[0 1 0 ... 0 0 0]
to_be_converted\4\gestures4486.jpg
[0 2 0 ... 0 0 0]
to_be_converted\4\gestures4487.jpg
[0 1 0 ... 0 0 0]
to_be_converted\4\gestures4488.jpg
[0 0 2 ... 0 0 0]
to_be_converted\4\gestures4489.jpg
[0 0 2 ... 0 0 0]
to_be_converted\4\gestures449.jpg
[  0   1   0 ... 255 252 255]
to_be_

[  0   3   0 ... 255 255 255]
to_be_converted\4\gestures4591.jpg
[  1   0   2 ... 255 255 254]
to_be_converted\4\gestures4592.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\4\gestures4593.jpg
[  0   1   0 ... 255 255 255]
to_be_converted\4\gestures4594.jpg
[  0   1   0 ... 255 255 255]
to_be_converted\4\gestures4595.jpg
[  0   3   0 ... 255 255 255]
to_be_converted\4\gestures4596.jpg
[  0   1   0 ... 255 255 255]
to_be_converted\4\gestures4597.jpg
[  0   2   0 ... 255 255   0]
to_be_converted\4\gestures4598.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\4\gestures4599.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\4\gestures46.jpg
[  0   0   2 ... 255 253 174]
to_be_converted\4\gestures460.jpg
[  0   0   3 ... 255 255 254]
to_be_converted\4\gestures4600.jpg
[  0   3   0 ... 255 254   0]
to_be_converted\4\gestures4601.jpg
[  0   1   0 ... 255 255 255]
to_be_converted\4\gestures4602.jpg
[  0   3   0 ... 255 252 227]
to_be_converted\4\gestures4603.jpg
[  0   3   0 ... 255 252 227

[  2   0   2 ... 255 255 255]
to_be_converted\4\gestures4710.jpg
[  0   0   0 ... 255 255 254]
to_be_converted\4\gestures4711.jpg
[  0   0   0 ... 255 255 254]
to_be_converted\4\gestures4712.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\4\gestures4713.jpg
[  0   2   0 ... 255 255 255]
to_be_converted\4\gestures4714.jpg
[  0   0   1 ... 255 255 255]
to_be_converted\4\gestures4715.jpg
[  0   0   1 ... 255 255 255]
to_be_converted\4\gestures4716.jpg
[  0   1   1 ... 255 255 255]
to_be_converted\4\gestures4717.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\4\gestures4718.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\4\gestures4719.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\4\gestures472.jpg
[  0   0   3 ... 255 255 255]
to_be_converted\4\gestures4720.jpg
[  0   0   0 ... 255 255 249]
to_be_converted\4\gestures4721.jpg
[  0   0   1 ... 255 255 255]
to_be_converted\4\gestures4722.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\4\gestures4723.jpg
[  0   0   0 ... 255 255 2

to_be_converted\4\gestures4828.jpg
[  1   0   1 ... 255 255  23]
to_be_converted\4\gestures4829.jpg
[  0   0   1 ... 255 255  23]
to_be_converted\4\gestures483.jpg
[  0   3   0 ... 255 255 255]
to_be_converted\4\gestures4830.jpg
[  1   1   0 ... 255 255 251]
to_be_converted\4\gestures4831.jpg
[  1   0   0 ... 255 255 255]
to_be_converted\4\gestures4832.jpg
[  1   0   2 ... 255 255 255]
to_be_converted\4\gestures4833.jpg
[  0   0   1 ... 255 255  23]
to_be_converted\4\gestures4834.jpg
[  0   0   1 ... 255 252 255]
to_be_converted\4\gestures4835.jpg
[  0   1   1 ... 255 252 255]
to_be_converted\4\gestures4836.jpg
[  1   0   0 ... 255 255 255]
to_be_converted\4\gestures4837.jpg
[  0   1   0 ... 255 255 255]
to_be_converted\4\gestures4838.jpg
[  0   2   0 ... 255 255 255]
to_be_converted\4\gestures4839.jpg
[  0   0   1 ... 255 255 255]
to_be_converted\4\gestures484.jpg
[  1   0   0 ... 255 253 255]
to_be_converted\4\gestures4840.jpg
[  0   0   1 ... 255 255 255]
to_be_converted\4\gestures4

to_be_converted\4\gestures4945.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\4\gestures4946.jpg
[  0   1   1 ... 255 255 255]
to_be_converted\4\gestures4947.jpg
[  0   1   1 ... 255 255 255]
to_be_converted\4\gestures4948.jpg
[  1   0   3 ... 255 255  45]
to_be_converted\4\gestures4949.jpg
[  0   4   0 ... 255 255 255]
to_be_converted\4\gestures495.jpg
[  0   2   0 ... 255 255 255]
to_be_converted\4\gestures4950.jpg
[  1   0   0 ... 255 255 254]
to_be_converted\4\gestures4951.jpg
[  1   0   0 ... 255 255 254]
to_be_converted\4\gestures4952.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\4\gestures4953.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\4\gestures4954.jpg
[  0   3   0 ... 255 255 255]
to_be_converted\4\gestures4955.jpg
[  0   2   1 ... 255 255 255]
to_be_converted\4\gestures4956.jpg
[  0   1   1 ... 255 252 255]
to_be_converted\4\gestures4957.jpg
[  0   0   2 ... 255 255 255]
to_be_converted\4\gestures4958.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\4\gestures

[0 0 0 ... 0 0 0]
to_be_converted\5\gestures51070.jpg
[0 1 0 ... 0 0 0]
to_be_converted\5\gestures51071.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures51072.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures51073.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures51074.jpg
[1 0 0 ... 0 0 0]
to_be_converted\5\gestures51075.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures51076.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures51077.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures51078.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures51079.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5108.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures51080.jpg
[2 0 0 ... 0 0 0]
to_be_converted\5\gestures51081.jpg
[2 0 0 ... 0 0 0]
to_be_converted\5\gestures51082.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures51083.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures51084.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures51085.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures51086.jpg
[0 0 0 ... 0 0 0]
to_be_conve

[0 0 0 ... 0 0 0]
to_be_converted\5\gestures513.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5130.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5131.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5132.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5133.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5134.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5135.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5136.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5137.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5138.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5139.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures514.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5140.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5141.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5142.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5143.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5144.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5145.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5146

[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5273.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5274.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5275.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5276.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5277.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5278.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5279.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures528.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5280.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5281.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5282.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5283.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5284.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5285.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5286.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5287.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5288.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5289.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures529

[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5554.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5555.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5556.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5557.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5558.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5559.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures556.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5560.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5561.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5562.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5563.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5564.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5565.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5566.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5567.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5568.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5569.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures557.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5570

[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5694.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5695.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5696.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5697.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5698.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5699.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures57.jpg
[0 0 0 ... 1 0 0]
to_be_converted\5\gestures570.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5700.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5701.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5702.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5703.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5704.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5705.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5706.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5707.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5708.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5709.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures571.j

to_be_converted\5\gestures5837.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5838.jpg
[0 0 2 ... 0 0 0]
to_be_converted\5\gestures5839.jpg
[0 1 0 ... 0 0 0]
to_be_converted\5\gestures584.jpg
[0 1 0 ... 0 0 0]
to_be_converted\5\gestures5840.jpg
[0 0 2 ... 0 0 0]
to_be_converted\5\gestures5841.jpg
[0 2 0 ... 0 0 0]
to_be_converted\5\gestures5842.jpg
[0 2 0 ... 0 0 0]
to_be_converted\5\gestures5843.jpg
[2 0 0 ... 0 0 0]
to_be_converted\5\gestures5844.jpg
[1 0 0 ... 0 0 0]
to_be_converted\5\gestures5845.jpg
[2 0 0 ... 0 0 0]
to_be_converted\5\gestures5846.jpg
[2 0 0 ... 0 0 0]
to_be_converted\5\gestures5847.jpg
[2 0 0 ... 0 0 0]
to_be_converted\5\gestures5848.jpg
[0 1 0 ... 0 0 0]
to_be_converted\5\gestures5849.jpg
[0 1 1 ... 0 0 0]
to_be_converted\5\gestures585.jpg
[0 1 0 ... 0 0 0]
to_be_converted\5\gestures5850.jpg
[0 1 0 ... 0 0 0]
to_be_converted\5\gestures5851.jpg
[0 1 0 ... 0 0 0]
to_be_converted\5\gestures5852.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5853.jpg
[0 0 1 ... 0 

[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5980.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5981.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5982.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5983.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5984.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5985.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5986.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5987.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5988.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5989.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures599.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5990.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5991.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5992.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5993.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5994.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5995.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures5996.jpg
[0 0 0 ... 0 0 0]
to_be_converted\5\gestures599

[2 0 0 ... 1 0 0]
to_be_converted\6\gestures61100.jpg
[255 255 255 ...   0   0   0]
to_be_converted\6\gestures61101.jpg
[255 255 255 ...   0   0   0]
to_be_converted\6\gestures61102.jpg
[254 255 254 ...   0   0   0]
to_be_converted\6\gestures61103.jpg
[255 254 255 ...   0   0   0]
to_be_converted\6\gestures61104.jpg
[255 254 255 ...   0   0   0]
to_be_converted\6\gestures61105.jpg
[255 255 255 ...   0   0   0]
to_be_converted\6\gestures61106.jpg
[254 255 253 ...   0   0   0]
to_be_converted\6\gestures61107.jpg
[255 255 255 ...   0   0   0]
to_be_converted\6\gestures61108.jpg
[255 255 254 ...   0   0   0]
to_be_converted\6\gestures61109.jpg
[255 254 255 ...   0   0   0]
to_be_converted\6\gestures6111.jpg
[2 0 0 ... 1 0 0]
to_be_converted\6\gestures61110.jpg
[171 255 253 ...   0   0   0]
to_be_converted\6\gestures61111.jpg
[255 253 255 ...   0   0   0]
to_be_converted\6\gestures61112.jpg
[  0   1 253 ...   0   0   0]
to_be_converted\6\gestures61113.jpg
[254 255 253 ...   1   0   0]
to_be

to_be_converted\6\gestures6139.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures614.jpg
[0 3 0 ... 0 0 0]
to_be_converted\6\gestures6140.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6141.jpg
[1 0 0 ... 0 0 0]
to_be_converted\6\gestures6142.jpg
[1 0 0 ... 0 0 0]
to_be_converted\6\gestures6143.jpg
[1 0 0 ... 0 0 0]
to_be_converted\6\gestures6144.jpg
[0 2 0 ... 0 0 0]
to_be_converted\6\gestures6145.jpg
[1 0 0 ... 3 0 0]
to_be_converted\6\gestures6146.jpg
[1 0 0 ... 0 0 0]
to_be_converted\6\gestures6147.jpg
[1 0 0 ... 0 0 0]
to_be_converted\6\gestures6148.jpg
[1 0 0 ... 0 0 0]
to_be_converted\6\gestures6149.jpg
[0 0 4 ... 0 0 0]
to_be_converted\6\gestures615.jpg
[1 0 0 ... 0 0 0]
to_be_converted\6\gestures6150.jpg
[1 0 0 ... 0 0 0]
to_be_converted\6\gestures6151.jpg
[1 0 0 ... 0 0 0]
to_be_converted\6\gestures6152.jpg
[2 0 0 ... 0 0 0]
to_be_converted\6\gestures6153.jpg
[1 0 0 ... 0 0 0]
to_be_converted\6\gestures6154.jpg
[1 0 0 ... 0 0 0]
to_be_converted\6\gestures6155.jpg
[0 2 0 ... 0 

[0 1 0 ... 2 0 0]
to_be_converted\6\gestures6281.jpg
[0 1 0 ... 2 0 0]
to_be_converted\6\gestures6282.jpg
[1 0 0 ... 0 0 0]
to_be_converted\6\gestures6283.jpg
[1 0 0 ... 2 0 0]
to_be_converted\6\gestures6284.jpg
[1 0 0 ... 2 0 0]
to_be_converted\6\gestures6285.jpg
[1 0 0 ... 0 0 0]
to_be_converted\6\gestures6286.jpg
[2 0 0 ... 0 0 0]
to_be_converted\6\gestures6287.jpg
[0 1 0 ... 2 0 0]
to_be_converted\6\gestures6288.jpg
[0 1 0 ... 0 0 0]
to_be_converted\6\gestures6289.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures629.jpg
[204 253 255 ...   0   0   0]
to_be_converted\6\gestures6290.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6291.jpg
[1 0 1 ... 0 0 0]
to_be_converted\6\gestures6292.jpg
[0 2 0 ... 0 0 0]
to_be_converted\6\gestures6293.jpg
[0 2 0 ... 0 0 0]
to_be_converted\6\gestures6294.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6295.jpg
[0 2 0 ... 0 0 0]
to_be_converted\6\gestures6296.jpg
[0 2 0 ... 0 0 0]
to_be_converted\6\gestures6297.jpg
[0 1 0 ... 0 0 0]
to_be_converted\6

to_be_converted\6\gestures6418.jpg
[0 0 2 ... 0 0 0]
to_be_converted\6\gestures6419.jpg
[0 2 0 ... 0 0 0]
to_be_converted\6\gestures642.jpg
[106 254 255 ...   0   0   0]
to_be_converted\6\gestures6420.jpg
[0 2 0 ... 0 0 0]
to_be_converted\6\gestures6421.jpg
[0 1 0 ... 0 0 0]
to_be_converted\6\gestures6422.jpg
[0 2 0 ... 0 0 0]
to_be_converted\6\gestures6423.jpg
[0 2 0 ... 0 0 0]
to_be_converted\6\gestures6424.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6425.jpg
[0 1 0 ... 0 0 0]
to_be_converted\6\gestures6426.jpg
[0 1 0 ... 0 0 0]
to_be_converted\6\gestures6427.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6428.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6429.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures643.jpg
[209 255 254 ...   0   0   0]
to_be_converted\6\gestures6430.jpg
[0 0 0 ... 2 0 0]
to_be_converted\6\gestures6431.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6432.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6433.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestur

[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6561.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6562.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6563.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6564.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6565.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6566.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6567.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6568.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6569.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures657.jpg
[  0 255 254 ...   0   0   0]
to_be_converted\6\gestures6570.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6571.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6572.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6573.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6574.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6575.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6576.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6577.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6

to_be_converted\6\gestures6701.jpg
[252 255 255 ... 255 158   0]
to_be_converted\6\gestures6702.jpg
[252 255 255 ... 255 158   0]
to_be_converted\6\gestures6703.jpg
[ 86  90 254 ... 255 254   0]
to_be_converted\6\gestures6704.jpg
[  1 254 255 ... 255 255 255]
to_be_converted\6\gestures6705.jpg
[ 90 175 255 ... 255 255 255]
to_be_converted\6\gestures6706.jpg
[  1 255 255 ... 255 255 255]
to_be_converted\6\gestures6707.jpg
[255 254 253 ... 255 255 255]
to_be_converted\6\gestures6708.jpg
[  0 255 255 ... 255 255 255]
to_be_converted\6\gestures6709.jpg
[168 254 254 ... 255 255 255]
to_be_converted\6\gestures671.jpg
[0 0 0 ... 1 0 0]
to_be_converted\6\gestures6710.jpg
[255 255 254 ... 255 255 126]
to_be_converted\6\gestures6711.jpg
[255 255 255 ... 255 255  89]
to_be_converted\6\gestures6712.jpg
[255 255 255 ... 255 255  89]
to_be_converted\6\gestures6713.jpg
[255 254 252 ... 255 254   0]
to_be_converted\6\gestures6714.jpg
[183 252 255 ... 255   0   0]
to_be_converted\6\gestures6715.jpg
[ 4

to_be_converted\6\gestures6828.jpg
[255 253 255 ...   0   0   0]
to_be_converted\6\gestures6829.jpg
[255 255 252 ...   0   0   0]
to_be_converted\6\gestures683.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6830.jpg
[255 254 255 ...   0   0   0]
to_be_converted\6\gestures6831.jpg
[254 255 252 ...   3   0   0]
to_be_converted\6\gestures6832.jpg
[255 254 189 ...   0   0   0]
to_be_converted\6\gestures6833.jpg
[  1 213 254 ...   0   0   0]
to_be_converted\6\gestures6834.jpg
[  0 255 254 ...   2   0   0]
to_be_converted\6\gestures6835.jpg
[254 254 229 ...   0   0   0]
to_be_converted\6\gestures6836.jpg
[254 254 229 ...   0   0   0]
to_be_converted\6\gestures6837.jpg
[255 250 255 ...   3   0   0]
to_be_converted\6\gestures6838.jpg
[255 255 255 ...   1   0   0]
to_be_converted\6\gestures6839.jpg
[ 59 254 255 ...   0   0   0]
to_be_converted\6\gestures684.jpg
[0 0 0 ... 0 0 0]
to_be_converted\6\gestures6840.jpg
[254 255 254 ...   0   0   0]
to_be_converted\6\gestures6841.jpg
[254 255 254 ...

to_be_converted\6\gestures6949.jpg
[198 255 254 ...   0   0   0]
to_be_converted\6\gestures695.jpg
[1 0 0 ... 0 0 0]
to_be_converted\6\gestures6950.jpg
[164 255 254 ...   0   0   0]
to_be_converted\6\gestures6951.jpg
[254 255 253 ...   0   0   0]
to_be_converted\6\gestures6952.jpg
[254 255 253 ...   0   0   0]
to_be_converted\6\gestures6953.jpg
[254 255 255 ...   0   0   0]
to_be_converted\6\gestures6954.jpg
[  0 255 254 ...   0   0   0]
to_be_converted\6\gestures6955.jpg
[255 250 255 ...   2   0   0]
to_be_converted\6\gestures6956.jpg
[163 255 254 ...   2   0   0]
to_be_converted\6\gestures6957.jpg
[163 255 254 ...   2   0   0]
to_be_converted\6\gestures6958.jpg
[  0 255 255 ...   0   0   0]
to_be_converted\6\gestures6959.jpg
[  0 229 255 ...   3   0   0]
to_be_converted\6\gestures696.jpg
[0 0 0 ... 2 0 0]
to_be_converted\6\gestures6960.jpg
[  0 229 255 ...   3   0   0]
to_be_converted\6\gestures6961.jpg
[  1 254 255 ...   3   0   0]
to_be_converted\6\gestures6962.jpg
[252 255 255 ...

[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures71062.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures71063.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures71064.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures71065.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures71066.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures71067.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures71068.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures71069.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7107.jpg
[  0   0   0 ... 255 254 255]
to_be_converted\7\gestures71070.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures71071.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures71072.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures71073.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures71074.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures71075.jpg
[  0   0   

[  0   3   0 ... 255 255 255]
to_be_converted\7\gestures7210.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7211.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7212.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7213.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7214.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7215.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7216.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7217.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7218.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7219.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures722.jpg
[  0   1   0 ... 255 255 255]
to_be_converted\7\gestures7220.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7221.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7222.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7223.jpg
[  0   0   0 ... 255 255 2

[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7332.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7333.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7334.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7335.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7336.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7337.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7338.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7339.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures734.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7340.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7341.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7342.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7343.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7344.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7345.jpg
[  0   0   0 ... 255 255 2

[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7451.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7452.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7453.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7454.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7455.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7456.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7457.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7458.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7459.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures746.jpg
[  0   0   0 ... 255 254  97]
to_be_converted\7\gestures7460.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7461.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7462.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7463.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7464.jpg
[  0   0   0 ... 255 255 2

to_be_converted\7\gestures7569.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures757.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7570.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7571.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7572.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7573.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7574.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7575.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7576.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7577.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7578.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7579.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures758.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7580.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7581.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7

[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7684.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7685.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7686.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7687.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7688.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7689.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures769.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7690.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7691.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7692.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7693.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7694.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7695.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7696.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7697.jpg
[  0   0   0 ... 255 255 2

[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7802.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7803.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7804.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7805.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7806.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7807.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7808.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7809.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures781.jpg
[  0   0   0 ... 255 252 255]
to_be_converted\7\gestures7810.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7811.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7812.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7813.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7814.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7815.jpg
[  0   0   0 ... 255 255 2

[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7917.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7918.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7919.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures792.jpg
[  0   0   0 ... 255 255  13]
to_be_converted\7\gestures7920.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7921.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7922.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7923.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7924.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7925.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7926.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7927.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7928.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures7929.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\7\gestures793.jpg
[  0   0   0 ... 255 254 15

[0 0 0 ... 0 0 0]
to_be_converted\8\gestures81035.jpg
[  0   0   0 ... 255   0   0]
to_be_converted\8\gestures81036.jpg
[  0   0   0 ... 254   0   0]
to_be_converted\8\gestures81037.jpg
[  0   0   0 ... 255   0   0]
to_be_converted\8\gestures81038.jpg
[  0   0   0 ... 242   0   0]
to_be_converted\8\gestures81039.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8104.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures81040.jpg
[0 0 0 ... 1 0 0]
to_be_converted\8\gestures81041.jpg
[  0   0   0 ... 217   0   0]
to_be_converted\8\gestures81042.jpg
[0 0 0 ... 1 0 0]
to_be_converted\8\gestures81043.jpg
[  0   0   0 ... 246   0   0]
to_be_converted\8\gestures81044.jpg
[0 0 0 ... 1 0 0]
to_be_converted\8\gestures81045.jpg
[  0   0   0 ... 232   0   0]
to_be_converted\8\gestures81046.jpg
[  0   0   0 ... 254   0   0]
to_be_converted\8\gestures81047.jpg
[  0   0   0 ... 245   0   0]
to_be_converted\8\gestures81048.jpg
[  0   0   0 ... 245   0   0]
to_be_converted\8\gestures81049.jpg
[0 0 

[  0   0   0 ... 254   0   0]
to_be_converted\8\gestures81163.jpg
[  0   0   0 ... 217   0   0]
to_be_converted\8\gestures81164.jpg
[  0   0   0 ... 217   0   0]
to_be_converted\8\gestures81165.jpg
[  0   0   0 ... 215   0   0]
to_be_converted\8\gestures81166.jpg
[  0   0   0 ... 254   0   0]
to_be_converted\8\gestures81167.jpg
[  0   0   0 ... 216   0   0]
to_be_converted\8\gestures81168.jpg
[  0   0   0 ... 255   0   0]
to_be_converted\8\gestures81169.jpg
[  0   0   0 ... 254   0   0]
to_be_converted\8\gestures8117.jpg
[  0   0   0 ... 255 255 253]
to_be_converted\8\gestures81170.jpg
[  0   0   0 ... 254   0   0]
to_be_converted\8\gestures81171.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures81172.jpg
[  0   0   0 ... 255 254   0]
to_be_converted\8\gestures81173.jpg
[  0   0   0 ... 255 254   0]
to_be_converted\8\gestures81174.jpg
[  0   0   0 ... 232   0   0]
to_be_converted\8\gestures81175.jpg
[  0   0   0 ... 255 143   2]
to_be_converted\8\gestures81176.jpg
[  0   0   0 ... 255 14

[  0   0   0 ... 255 253 188]
to_be_converted\8\gestures8202.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8203.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8204.jpg
[  0   0   0 ... 255 251 227]
to_be_converted\8\gestures8205.jpg
[  0   0   0 ... 255 255 220]
to_be_converted\8\gestures8206.jpg
[  0   0   0 ... 255 255 254]
to_be_converted\8\gestures8207.jpg
[  0   0   0 ... 255 255 254]
to_be_converted\8\gestures8208.jpg
[  0   0   0 ... 255 252 229]
to_be_converted\8\gestures8209.jpg
[  0   0   0 ... 255 252 229]
to_be_converted\8\gestures821.jpg
[  0   0   0 ... 255 255 106]
to_be_converted\8\gestures8210.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8211.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8212.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8213.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8214.jpg
[  0   0   0 ... 255 255 216]
to_be_converted\8\gestures8215.jpg
[  0   0   0 ... 255 255 2

[  0   0   0 ... 255 255 221]
to_be_converted\8\gestures8317.jpg
[  0   0   0 ... 255 255 228]
to_be_converted\8\gestures8318.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8319.jpg
[  0   0   0 ... 255 255 173]
to_be_converted\8\gestures832.jpg
[  0   0   0 ... 255 255 253]
to_be_converted\8\gestures8320.jpg
[  0   0   0 ... 255 255 173]
to_be_converted\8\gestures8321.jpg
[  0   0   0 ... 255 255 104]
to_be_converted\8\gestures8322.jpg
[  0   0   0 ... 255 251 227]
to_be_converted\8\gestures8323.jpg
[  0   0   0 ... 255 251 227]
to_be_converted\8\gestures8324.jpg
[  0   0   0 ... 255 255   0]
to_be_converted\8\gestures8325.jpg
[  0   0   0 ... 255 255   0]
to_be_converted\8\gestures8326.jpg
[  0   0   0 ... 255 255   0]
to_be_converted\8\gestures8327.jpg
[  0   0   0 ... 255 255   0]
to_be_converted\8\gestures8328.jpg
[  0   0   0 ... 255 254 176]
to_be_converted\8\gestures8329.jpg
[  0   0   0 ... 255 254 176]
to_be_converted\8\gestures833.jpg
[  0   0   0 ... 255 255 25

to_be_converted\8\gestures8434.jpg
[  0   0   0 ... 255 255 253]
to_be_converted\8\gestures8435.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8436.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8437.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8438.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8439.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures844.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8440.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8441.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8442.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8443.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8444.jpg
[  0   0   0 ... 255 254 255]
to_be_converted\8\gestures8445.jpg
[  0   0   0 ... 255 254 255]
to_be_converted\8\gestures8446.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8447.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures

[  0   0   0 ... 255 255 143]
to_be_converted\8\gestures8549.jpg
[  0   0   0 ... 255 255 143]
to_be_converted\8\gestures855.jpg
[  0   0   0 ... 255 255 254]
to_be_converted\8\gestures8550.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8551.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8552.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8553.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8554.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8555.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8556.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8557.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8558.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8559.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures856.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8560.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8561.jpg
[  0   0   0 ... 255 255 25

[  0   0   0 ... 255   0   0]
to_be_converted\8\gestures8677.jpg
[  0   0   0 ... 216   0   0]
to_be_converted\8\gestures8678.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8679.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures868.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8680.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8681.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8682.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8683.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8684.jpg
[0 0 0 ... 1 0 0]
to_be_converted\8\gestures8685.jpg
[0 0 0 ... 1 0 0]
to_be_converted\8\gestures8686.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8687.jpg
[0 0 0 ... 2 0 0]
to_be_converted\8\gestures8688.jpg
[0 0 0 ... 2 0 0]
to_be_converted\8\gestures8689.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures869.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8690.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8691.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8692.jpg


[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8812.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8813.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8814.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8815.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8816.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8817.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8818.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8819.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures882.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\8\gestures8820.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8821.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8822.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8823.jpg
[0 0 0 ... 1 0 0]
to_be_converted\8\gestures8824.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8825.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8826.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8827.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8828.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8

to_be_converted\8\gestures8954.jpg
[  0   0   0 ... 211   0   0]
to_be_converted\8\gestures8955.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8956.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8957.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8958.jpg
[  0   0   0 ... 252   0   0]
to_be_converted\8\gestures8959.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures896.jpg
[  0   0   0 ... 255 255 162]
to_be_converted\8\gestures8960.jpg
[0 0 0 ... 1 0 0]
to_be_converted\8\gestures8961.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8962.jpg
[  0   0   0 ... 252 254   0]
to_be_converted\8\gestures8963.jpg
[  0   0   0 ... 198   0   0]
to_be_converted\8\gestures8964.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8965.jpg
[  0   0   0 ... 254   0   0]
to_be_converted\8\gestures8966.jpg
[  0   0   0 ... 254   0   0]
to_be_converted\8\gestures8967.jpg
[  0   0   0 ... 254   0   0]
to_be_converted\8\gestures8968.jpg
[0 0 0 ... 0 0 0]
to_be_converted\8\gestures8969.jpg
[0 0 0 ... 0 0 0]
to_b

[  0   0   0 ... 255 254 254]
to_be_converted\9\gestures91071.jpg
[  0   0   0 ... 255 254 254]
to_be_converted\9\gestures91072.jpg
[  0   0   0 ... 255 253 255]
to_be_converted\9\gestures91073.jpg
[  0   0   0 ... 255 255 128]
to_be_converted\9\gestures91074.jpg
[  0   0   0 ... 255 255 128]
to_be_converted\9\gestures91075.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures91076.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures91077.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures91078.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures91079.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9108.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures91080.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures91081.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures91082.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures91083.jpg
[  0   0   0 ... 255 255 129]
to_be_converted\9\gestures91084.jpg
[  0   0   

to_be_converted\9\gestures91185.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures91186.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures91187.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures91188.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures91189.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9119.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures91190.jpg
[  0   0   0 ... 255 255 109]
to_be_converted\9\gestures91191.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures91192.jpg
[  0   0   0 ... 255 255   0]
to_be_converted\9\gestures91193.jpg
[  0   0   0 ... 255 255   0]
to_be_converted\9\gestures91194.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures91195.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures91196.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures91197.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures91198.jpg
[  0   0   0 ... 255 255 255]
to_be_conve

[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9224.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9225.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9226.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9227.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9228.jpg
[  0   0   0 ... 255 254 255]
to_be_converted\9\gestures9229.jpg
[  0   0   0 ... 255 254 255]
to_be_converted\9\gestures923.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9230.jpg
[  0   0   0 ... 255 253 255]
to_be_converted\9\gestures9231.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9232.jpg
[  0   0   0 ... 255 255  66]
to_be_converted\9\gestures9233.jpg
[  0   0   0 ... 255 254 255]
to_be_converted\9\gestures9234.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9235.jpg
[  0   0   0 ... 255 254 102]
to_be_converted\9\gestures9236.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9237.jpg
[  0   0   0 ... 255 255 2

[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9341.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9342.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9343.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9344.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9345.jpg
[  0   0   0 ... 255 255 251]
to_be_converted\9\gestures9346.jpg
[  0   0   0 ... 255 255 251]
to_be_converted\9\gestures9347.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9348.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9349.jpg
[  0   0   0 ... 255 254 168]
to_be_converted\9\gestures935.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9350.jpg
[  0   0   0 ... 255 254 255]
to_be_converted\9\gestures9351.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9352.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9353.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9354.jpg
[  0   0   0 ... 255 255 2

[  0   0   0 ... 255 255 253]
to_be_converted\9\gestures9467.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9468.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9469.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures947.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9470.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9471.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9472.jpg
[  0   0   0 ... 255 255 254]
to_be_converted\9\gestures9473.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9474.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9475.jpg
[  0   0   0 ... 255 254 254]
to_be_converted\9\gestures9476.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9477.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9478.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9479.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures948.jpg
[  0   0   0 ... 255 255 22

[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9584.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9585.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9586.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9587.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9588.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9589.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures959.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9590.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9591.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9592.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9593.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9594.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9595.jpg
[  0   0   0 ... 255 255 119]
to_be_converted\9\gestures9596.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9597.jpg
[  0   0   0 ... 255 255 2

to_be_converted\9\gestures9702.jpg
[  0   0   0 ... 255 255 104]
to_be_converted\9\gestures9703.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9704.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9705.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9706.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9707.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9708.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9709.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures971.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9710.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9711.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9712.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9713.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9714.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9715.jpg
[  0   0   0 ... 255 255 252]
to_be_converted\9\gestures

[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9817.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9818.jpg
[  0   0   0 ... 255 253 255]
to_be_converted\9\gestures9819.jpg
[  0   0   0 ... 255 253 255]
to_be_converted\9\gestures982.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9820.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9821.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9822.jpg
[  0   0   0 ... 255 252 255]
to_be_converted\9\gestures9823.jpg
[  0   0   0 ... 255 252 255]
to_be_converted\9\gestures9824.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9825.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9826.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9827.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9828.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9829.jpg
[  0   0   0 ... 255 255 109]
to_be_converted\9\gestures983.jpg
[  0   0   0 ... 255 255 25

to_be_converted\9\gestures9932.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9933.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9934.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9935.jpg
[  0   0   0 ... 255 254 253]
to_be_converted\9\gestures9936.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9937.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9938.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9939.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures994.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9940.jpg
[  0   0   0 ... 255 255 255]
to_be_converted\9\gestures9941.jpg
[  0   0   0 ... 255 255 253]
to_be_converted\9\gestures9942.jpg
[  0   0   0 ... 255 255 253]
to_be_converted\9\gestures9943.jpg
[  0   0   0 ... 255 255 104]
to_be_converted\9\gestures9944.jpg
[  0   0   0 ... 255 255 104]
to_be_converted\9\gestures9945.jpg
[  0   0   0 ... 255 255 252]
to_be_converted\9\gestures